<?php

use App\Models\Apartment;
use App\Models\Hotel;
use App\Models\Listing;
use PHPUnit\Framework\TestCase;
use SimpleCli\SimpleCli;

class DefaultControllerTest extends TestCase
{
    protected $ids = [];

    protected function setUp(): void{
        parent::setUp();

        $hotel = new Hotel();
        $hotelData = ['Hotel Test', 5,1,1,1 ];
        $newHotel = $hotel->create($hotelData);

        $listingData[] = ['hotels', $newHotel['id']];
        $this->ids['App\Models\Hotel'][] = $newHotel['id'];

        $apartment = new Apartment();
        $apartmentData = ['Apartments Test', 5,4,1,1 ];
        $newApartment =  $apartment->create($apartmentData);
        $listingData[] = ['apartments', $newApartment['id']];
        $this->ids['App\Models\Apartment'][] = $newApartment['id'];

        $listing = new Listing();
        foreach ($listingData as $data) {
            $newListing = $listing->create($data);
            $this->ids['App\Models\Listing'][] = $newListing['id'];
        }

    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        foreach ($this->ids as $table =>$ids) {

            $model = new $table;

            foreach ($ids as $id){
                $model->delete($id);
            }
        }
    }

    public function testHandleSearch()
    {
        $argv = ['index.php','search','default',"name=Test"];
        $app = new SimpleCli();
        ob_start();
        $app->runCommand($argv);
        $output = ob_get_contents();
        ob_end_clean();

        $this->assertEquals(
            "Hotel Test,5,Habitación doble con vistas,Valencia,Valencia\nApartments Test,5,4,Valencia,Valencia\n", $output );
        $this->tearDown();
    }
}